# Funding options for Greed.js

github: # Add your GitHub Sponsors username
patreon: # Add your Patreon username
open_collective: # Add your Open Collective username
ko_fi: # Add your Ko-fi username
custom: # Add custom sponsorship URL if desired
